name: Deployment
run-name: ${{ github.actor }} is deploying

concurrency:
  group: production
  cancel-in-progress: true

on:
  push:
    branches:
      - main

jobs:
  Deployment:
    needs: Build
    runs-on: self-hosted
    environment: production
    steps:
      - name: deploying
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.TRADER_HOST }}
          username: ${{ secrets.TRADER_USERNAME }}
          key: ${{ secrets.TRADER_KEY }}
          script: |
            docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/toc-sinopac-python:latest
