name: Lint, Build, and Deployment
run-name: ${{ github.actor }} is running TOC SINOPAC PYTHON Actions 🚀

concurrency:
  group: production
  cancel-in-progress: true

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  Lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10.6"

      - name: Install Requirements
        run: |
          pip install --no-warn-script-location --no-cache-dir -r requirements.txt
          pip install --no-warn-script-location --no-cache-dir mypy-protobuf pylint-protobuf mypy pylint
          mypy --install-types --non-interactive ./src

      - name: Lint
        run: |
          export PYTHONPATH=$(pwd)/pb
          echo $PYTHONPATH
          export PYLINTHOME=$(pwd)
          echo $PYLINTHOME
          ./scripts/lint-code.sh

  Build:
    needs: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v3.1.1
        with:
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/toc-sinopac-python:latest
          build-args: |
            "SSH_PRIVATE_KEY=${{ secrets.TIMHSU_KEY }}"

  Deployment:
    needs: Build
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: deploying
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.TRADER_HOST }}
          username: ${{ secrets.TRADER_USERNAME }}
          key: ${{ secrets.TRADER_KEY }}
          script: |
            mkdir -p ~/toc-sinopac-python-env"
            echo ${{ secrets.SINOPAC_ENV }} > ~/toc-sinopac-python-env/.env

            docker kill toc-sinopac-python || true
            docker rmi ${{ secrets.DOCKERHUB_USERNAME }}/toc-sinopac-python:latest || true
            docker system prune --volumes -f

            docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/toc-sinopac-python:latest
            docker run \
              --name toc-sinopac-python \
              --network tocvlan \
              --ip=172.20.10.227 \
              --restart always \
              -e TZ="Asia/Taipei" \
              -v ~/toc-sinopac-python-logs:/toc-sinopac-python/logs \
              -v ~/toc-sinopac-python-env/.env:/toc-sinopac-python/.env \
              -dt $IMAGE_TAG
