name: Stop-Deployment
run-name: ${{ github.actor }} is stopping deployment

on:
  workflow_dispatch:

jobs:
  Stop-Deployment:
    runs-on: ubuntu-latest
    steps:
      - name: deploying
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.TRADER_HOST }}
          username: ${{ secrets.TRADER_USERNAME }}
          key: ${{ secrets.TRADER_KEY }}
          script: |
            docker rmi ${{ secrets.DOCKERHUB_USERNAME }}/toc-sinopac-python:latest

      - name: deactivate deployments
        uses: strumwolf/delete-deployment-environment@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          environment: production
          onlyDeactivateDeployments: true
